### ISSUE TITLE
Create a mockup for the authentication/account creation screen

### ISSUE THREAD

**Issue by Energiiz** [MediBlog/Android-Application#6]
A mockup with all the labels and textfields for an account creation and an authentication

**Comment by ggnumber01** [comment]
do the login:
http://hmkcode.com/android-designing-a-login-screen-sign-in-sign-up-screens/
save the login:
http://stackoverflow.com/questions/12744337/how-to-keep-android-applications-always-be-logged-in-state

**Comment by DoRBIRD** [comment]
Done - Push number: 3d908637a3bf8a76968d567a230f7fd74350d4d0
